# Generated by Django 4.0.6 on 2022-07-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_view_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profil_picture',
            new_name='profile_picture',
        ),
    ]
