# Generated by Django 4.0.6 on 2022-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('kriptopara', 'kriptopara'), ('blockchain', 'blockchain'), ('indikator', 'indikator'), ('analiz', 'analiz'), ('haber', 'haber'), ('projeinceleme', 'projeinceleme')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
